service: ipa
org: carioca
frameworkVersion: '>=1.28.0 <2.0.0'

plugins:
  - serverless-domain-manager
  - serverless-offline
  - serverless-offline-sns

custom:
  customDomain:
    domainName: ipa.painel.ml
    basePath: ${opt:stage, 'dev'}
    stage: ${opt:stage, 'dev'}
    createRoute53Record: true
  serverless-offline-sns:
    port: 4002
    debug: true

provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  memorySize: 128
  timeout: 15
  apiKeys: ${file(env/${opt:stage}.yml):provider.apiKeys}
  profile: ${file(env/${opt:stage}.yml):provider.profile}
  tags:
    App: ${self:service}
    Env: ${file(env/${opt:stage}.yml):tags.Env}
    Squad: carioca

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  renevue:
    handler: bin/renevue/month
    events:
      - http:
          path: renevue/month
          method: get